version: '3.8'

services:
  db-voting:
    image: postgres:latest
    container_name: db-voting
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 230502
    networks:
      - network-voting

  be-voting:
    image: be-voting
    container_name: be-voting
    ports:
      - "8080:8080"
    # environment:
    #   DATABASE_URL: postgresql://postgres:230502@db-voting:5432/postgres?schema=public
    depends_on:
      - db-voting
    networks:
      - network-voting

networks:
  network-voting:
    driver: bridge
